Elico-Corp/odoo-docker

Dockerfile, sources/pip-req.txt
=>  	Upgrade Pillow through the dependancies file

Dockerfile, sources/pip-req.txt
=> Upgrade Pillow through the dependancies file

README.md
This reverts commit 13885936f4c4f427e738c7b0a88fb07fbe8cd605.
=> CN version is not based on XCGD project

Dockerfile
=> modify pg to 9.5

sources/pip-req.txt
please don't merge , I'm testing it now.
=> [FIX] upgrade pyparsing to  2.1.10

Dockerfile
See https://bitbucket.org/xcgd/odoo/commits/e495b56328e65e4fdc9d3f884bdf04b67bc87e6d?at=8.0
=> Backport XCGD Py3O dependencies

bin/boot
=> Backport #65 to v9

Dockerfile, bin/boot, bin/no_addons.sh, bin/target_user.sh, bin/update_odoo_param.sh
=> [MRG][8.0.1.0] Port #78

Dockerfile, bin/boot
=> [MRG][8.0.1.0] Port #86

Dockerfile, bin/boot
=> [MRG][9.0.1.0] Port #86

Dockerfile, bin/boot
=> [MRG][10.0.1.0] Port #86

Dockerfile
=> [MRG][8.0.1.0] Port #90

Dockerfile
=> [MRG][9.0.1.0] Port #90

Dockerfile
=> [MRG][10.0.1.0] Port #90

README.md, auto_addons/addons.py
=> [WIP][7.0] Refactor auto addons to fix addons_path for Odoo standard addons

README.md, auto_addons/addons.py
=> [MRG][8.0.1.1] Port #98

Dockerfile, README.md, auto_addons/addons.py, sources/pip-req.txt
=> [MRG][8.0] Merge 8.0.1.1 into main branch

Dockerfile, README.md, auto_addons/addons.py, sources/pip-req.txt
Changelog, see:
- 2e715f0
- 346e4e6
- 369ff8a
=> [MRG][7.0] Merge 7.0.1.1 into main branch

Dockerfile
Reverts Elico-Corp/odoo-docker#124
=> Revert "no need to download Odoo git history"

sources/apt.txt
=> [UPD] Update PostgreSQL to v10
